### ISSUE TITLE
URI.expand() is missing

### ISSUE THREAD

**Issue by suriyanto** [medialize/URI.js#246] opened 2015-08-26 23:55 UTC
I upgraded from v1.15.1 and have just realized that URI.expand() function is now missing. Is there a replacement method to perform URI parameters expansion?

**Comment by rodneyrehm** [comment] 2015-08-27 07:40
That method should not be missing if you properly loaded `src/URITemplate.js`

**Comment by suriyanto** [comment] 2015-08-27 08:01
Thanks for the reply.

Yes, the method exist in URITemplate, but URITemplate is not instantiable from outside anymore, right? So the example shows that I can use the expand() method from URI, but I can't seem to execute that function and I can't find it in the source code (URI.js).

Am I missing something that should be loaded properly?

**Comment by rodneyrehm** [comment] 2015-08-27 08:08
> Yes, the method exist in URITemplate, but URITemplate is not instantiable from outside anymore, right? 

Why wouldn't it be?

```js
var tpl = URITemplate('baz{foo}');
tpl.expand({ foo: 'bar' });
```

works fine on my end

> So the example shows that I can use the expand() method from URI, but I can't seem to execute that function and I can't find it in the source code (URI.js).

yes, because it is added by [URITemplate.js](https://github.com/medialize/URI.js/blob/gh-pages/src/URITemplate.js#L491-L496)

**Comment by rodneyrehm** [comment] 2015-09-01 23:27
@suriyanto are you still experiencing problems?

**Comment by rodneyrehm** [comment] 2015-09-26 10:10
closing because there's no feedback from OP and issue could not be reproduced on my end.

**Closed by rodneyrehm** 2015-09-26 10:10 UTC

**Comment by guioconnor** [comment] 2016-08-23 16:37
Hi, I was facing a similar problem to @suriyanto.

I can see the URITemplate file and the `expand()` method within but how can it be `require()`'d without breaking the package encapsulation?

The Readme suggests this, which has worked for me...
```var URITemplate = require('urijs/src/URITemplate');```

...but isn't the beauty of packages that you can abstract the internal implementation and rely on its manifest to use them?
